# Nom du pipeline
name: E2E CI/CD Cypress +  PHP + Apache + MySQL
# Déclencheurs push et pull request github
on:
  push:
    branches: [ "test", "main" ]
  pull_request:
    branches: [ "test" , "main"]
  workflow_dispatch:

jobs:
  # Nom du CI/CD 
  ci-cd:
    runs-on: ubuntu-latest
    # Service Base de données MySQL
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: TestPassword@1234
          MYSQL_DATABASE: taskdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -prootpw"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    # Etapes du pipeline
    steps:
      # Récupération du code
      - name: Checkout
        uses: actions/checkout@v4

      # Installation de PHp et Composer
      - name: Setup PHP CLI (Composer & outils)
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql, sodium, zip
          coverage: none
          tools: composer
      # Créer le fichier env
      - name: Creer fichier env
        run: |
        cat > env.php <<'PHP'
        <?php
        const BDD_LOGIN = "root";
        const BDD_PASSWORD = "TestPassword@1234";
        const BDD_SERVER = "127.0.0.1";
        const BDD_NAME = "taskdb";
        const BASE_URL = "/";
        PHP
      # Installer les dépendances PHP
      - name: Composer install
        run: |
          composer install
      # Migration BDD
      - name: Migration BDD
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -pTestPassword@1234 < base.sql
      # Démarrer le serveur PHP
      - name: Start serveur PHP
        run: |
          php -S 107.0.0.1:8000
      # Installer et démarrer les tests Cypress
      - name: Test Cypress
        uses: cypress-io/github-action@v6

